// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqeeojvB1WB3zv_fGwrAUiYPLJF7HRRVI',
    appId: '1:421292835026:web:e37b10d73bc1f5a467ed0b',
    messagingSenderId: '421292835026',
    projectId: 'publicnotes',
    authDomain: 'publicnotes.firebaseapp.com',
    storageBucket: 'publicnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWGpoc5syiXURYCjla3Ul0YkpG12CTnyw',
    appId: '1:421292835026:android:11143bf71835d46b67ed0b',
    messagingSenderId: '421292835026',
    projectId: 'publicnotes',
    storageBucket: 'publicnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUxt0OuhbupgUhh7EO73huuNuVNNrHJS4',
    appId: '1:421292835026:ios:d8300f6d442d780f67ed0b',
    messagingSenderId: '421292835026',
    projectId: 'publicnotes',
    storageBucket: 'publicnotes.appspot.com',
    iosBundleId: 'com.example.firebaserw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUxt0OuhbupgUhh7EO73huuNuVNNrHJS4',
    appId: '1:421292835026:ios:efdfaac35e50bea967ed0b',
    messagingSenderId: '421292835026',
    projectId: 'publicnotes',
    storageBucket: 'publicnotes.appspot.com',
    iosBundleId: 'com.example.firebaserw.RunnerTests',
  );
}
